version: "3.9"
services:
  db:
    image: postgres:15
    container_name: imoveis-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
